apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendstore-deployment
  labels:
    app: trendstore
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trendstore
  template:
    metadata:
      labels:
        app: trendstore
    spec:
      containers:
      - name: trendstore
        image: trend-store-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: trendstore-service
  labels:
    app: trendstore
spec:
  selector:
    app: trendstore
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
